server:
  port: 5678

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

openapi:
  service:
    api-docs: api-service
    server: http://localhost:5678
    title: API Service
    version: 1.0.0

api:
  prefix: /api/v1/

jwt:
  expiration: 3600  # 10 phut
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=